POST  http://127.0.0.1:3000/v1/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123",
    "email": "aselole@gmail.com",
    "firstName": "",
    "lastName": "",
    "classes": "X",
    "major_id": 1 ,
    "gender": "F"
}
###
POST  http://127.0.0.1:3000/send-message
Content-Type: application/json

{
    "message": "Hello, this is a test message."
}
###
PUT   http://127.0.0.1:3000/student/2
Content-Type: application/json

{
    "firstName": "Andriane",
    "lastName": "Fletcher",
    "major_id": 7,
    "classes": "XII",
    "gender": "F"
}
###

GET http://127.0.0.1:3000/student/2

###
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

###
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

###
POST http://127.0.0.1:3000/send-message
Content-Type: application/json

{
    "message": "Hello, this is a test message!",
    "name": "John Doe"
}

###
POST http://127.0.0.1:3000/v1/auth/register
